### ISSUE TITLE
Support high availability for the admission webhooks

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4437]
**What is missing?**

The ability to run the admission endpoints (/admission-prometheusrules/validate, /admission-prometheusrules/mutate and /admission-alertmanagerconfigs/validate) in HA.

**Why do we need it?**

Right now, you can configure `ValidatingWebhookConfiguration` resources pointing to the operator's service but you can't deploy 2 replicas of the operator since otherwise they would step on each other's toes during reconciliation. As such the admission service isn't highly-available so you either configure the validating webhook to ignore unrecognized errors (`failurePolicy: Ignore`) or you accept that users can't create/update resources when the operator is down/unreachable. Both options aren't ideal.

Possible options:
1. Have a standalone binary that only exposes the admission webhooks (no reconciliation).
2. Implement leader election in the operator.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Tasks**

- [ ] Split codebase (standalone admission webhook binary)
- [ ] Create the container image repositories (quay.io + ghcr.io)
- [ ] Update CI to push the new container image 
- [ ] Add e2e tests for the admission webhook
- [ ] Update kube-prometheus

**Comment by paulfantom** [comment]
I think a separate binary might be easier to implement and maintain so I vote for that solution.

**Comment by PhilipGough** [comment]
@simonpasquier perhaps we can get a checklist of tasks into #4437 as acceptance criteria so it might be easier to break up and review the work? Saying that I am happy to do it all in one PR if preferred. Some things that come to mind

- [ ] Split codebase
- [ ] Build image 
- [ ] Update CI
- [ ] Jsonnet?  
- [ ] Incorporate HA deploy into e2e tests
...

**Comment by simonpasquier** [comment]
@PhilipGough sgtm, I've updated the issue's description. Let me know if you see anything missing/incorrect.

**Comment by shreyas-badiger** [comment]
@simonpasquier is there any blocker to merge this PR? We are waiting on this one. The other option was to see how we could implement leader-election for Prometheus-operator. Please share if this PR is going in or not.

**Comment by PhilipGough** [comment]
@shreyas-badiger - this was implemented by #4494 

Closing based on that.
