### ISSUE TITLE
Support Kubernetes Node Monitoring using ScrapeConfig

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#5711]
This is related to https://github.com/prometheus-operator/prometheus-operator/issues/5509 but creating a new issue for tracking this for Kubernetes Node  Discovery. This is to support `role:node`  in [kubernetes_sd_configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config). Implement this feature using ScrapeConfig CRD

**TODO:**
- [x] [Support http Scheme in ScrapeConfig CRD](https://github.com/prometheus-operator/prometheus-operator/pull/5679)
- [x] [Support TLSConfig in ScrapeConfig CRD](https://github.com/prometheus-operator/prometheus-operator/pull/5710)
- [x] [Support Kubernetes Node Monitoring in ScrapeConfig CRD ](https://github.com/prometheus-operator/prometheus-operator/pull/5675)
- [x] [Add selector to filter nodes to monitor](https://github.com/prometheus-operator/prometheus-operator/pull/6053)

**What is missing?**

Currently we cannot monitor a Kubernetes node with CRD

**Why do we need it?**

Feature parity with upstream Prometheus

**Environment**

NA

* Prometheus Operator version:

NA
    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by bsloeserwij** [comment]
We tried to implement the code merged in #5675, by using the latest release (v0.67.1). After applying the following scrapeConfig:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: etcd-scrape-config
  namespace: test
  labels:
    release: kube-prometheus-stack
spec:
  kubernetesSDConfigs:
    - role: "Node"
```

the following config was generated (live from the kube-prometheus-stack container)
```
- job_name: scrapeconfig/niti-services/etcd-scrape-config                                                                                                                                                                                                                                
  kubernetes_sd_configs: null  

```
It seems that the value given in the ScrapeConfig is not transferred to the configuration of Prometheus.

After some additional research we found that the value of Spec.KubernetesSDConfigs are not appended to cfg: https://github.com/prometheus-operator/prometheus-operator/blob/be71cb80b0587d5f8895cfc675e6cc8a6e2d3d3d/pkg/prometheus/promcfg.go#L2350-L2352
If we are not mistaking the following line should be inserted before line 2352: `Value: configs`
Unfortunately we don't have a way of building the GO application and test the potential fix.

**Comment by simonpasquier** [comment]
Thanks for pointing out! The regression has been introduced in https://github.com/prometheus-operator/prometheus-operator/pull/5709/files#diff-453ce9c721c51bf9591c2b212e9ce50157b9c40d1b211177bf502be268099656L2298. Unfortunately we lack a unit test that would have caught the problem (but not sure why the e2e test didn't detect it).

**Comment by slashpai** [comment]
Thanks for reporting the issue. I will debug why e2e test didn't fail. Will submit the bugfix patch

**Comment by slashpai** [comment]
I ran the e2e test locally and I see e2e test is failed for `ScrapeConfigKubeNode`

https://github.com/prometheus-operator/prometheus-operator/blob/03cd78e55729d71bcedc2675cf654f10421b7486/test/e2e/scrapeconfig_test.go#L243-L329

For consulsd PR I see this e2e test was skipped https://github.com/prometheus-operator/prometheus-operator/actions/runs/5551435729/job/15185724327?pr=5709#step:9:359 likely due to `skipPrometheusTests(t)` in test 🤦🏻‍♀️ 

I have created https://github.com/prometheus-operator/prometheus-operator/issues/5870 for the bug. I will update the e2etest first and see if it fails and then add the fix in promcfg

**Comment by zuozp8** [comment]
is there a reason to allow only `role: Node` role? 'Service' role would be useful to me and I don't see (yet) any code that would handle the ScrappingConfigs with `role: Node` is a special way that shouldn't be applied to other roles

**Comment by ArthurSens** [comment]
> is there a reason to allow only `role: Node` role? 'Service' role would be useful to me and I don't see (yet) any code that would handle the ScrappingConfigs with `role: Node` is a special way that shouldn't be applied to other roles

No special reason at all to not have the other roles, it just wasn't contributed yet :) 

Contributions are welcome!

**Comment by zuozp8** [comment]
unfortunatelly no golang skills here

**Comment by slashpai** [comment]
> is there a reason to allow only `role: Node` role? 'Service' role would be useful to me and I don't see (yet) any code that would handle the ScrappingConfigs with `role: Node` is a special way that shouldn't be applied to other roles

We didn't have a native way to do Kubernetes node monitoring but we already have servicemonitor and podmonitor available for service and pods so node was a priority for ScrapeConfig kuberntesSDConfig .

**Comment by zuozp8** [comment]
ServiceMonitor creates a scrape_config with `role: endpoints`

my use-case is following: I have metrics that are computed from db - no point in calling it for each pod

I'll just keep using `additionalScrapeConfigs` for now (although it's not DRY, I repeat a lot between prod/staging/dev clusters)

**Comment by slashpai** [comment]
sure, idea is to support all roles in kubernetesSDConfigs I can log issues for same :)

Will this solution https://github.com/prometheus-operator/prometheus-operator/discussions/4770#discussioncomment-2687088 work you for now using serviceMonitors?

**Comment by zuozp8** [comment]
for me it's hassle to go into other projects and change their helm files; in the past I told my colleagues that they just add a label to their service and prometheus will handle everything :D

for now I'll stick to additionalScrapeConfigs and wait for all roles support
